#############################################################################
# Makefile for building: vmc
# Generated by qmake (2.01a) (Qt 4.8.0) on: Thu Feb 2 17:03:18 2012
# Project:  vmc.pro
# Template: app
# Command: /home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -spec /home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++-64 -o Makefile vmc.pro
#############################################################################

####### Compiler, tools and options

CC            = mpicc
CXX           = mpic++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++-64 -I. -I/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtCore -I/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/include -I.
LINK          = mpic++
LFLAGS        = -pthread -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -lopen-rte -lopen-pal -Wl,--export-dynamic -lnsl -lutil -lm -ldl -Wl,-O1 -Wl,-rpath,/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		matrix.cpp 
OBJECTS       = main.o \
		matrix.o
DIST          = /home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		vmc.pro
QMAKE_TARGET  = vmc
DESTDIR       = 
TARGET        = vmc

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: vmc.pro  /home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++-64/qmake.conf /home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++-64 -o Makefile vmc.pro
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
/home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /home/svenni/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++-64 -o Makefile vmc.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/vmc1.0.0 || $(MKDIR) .tmp/vmc1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/vmc1.0.0/ && $(COPY_FILE) --parents matrix.h .tmp/vmc1.0.0/ && $(COPY_FILE) --parents main.cpp matrix.cpp .tmp/vmc1.0.0/ && (cd `dirname .tmp/vmc1.0.0` && $(TAR) vmc1.0.0.tar vmc1.0.0 && $(COMPRESS) vmc1.0.0.tar) && $(MOVE) `dirname .tmp/vmc1.0.0`/vmc1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/vmc1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

matrix.o: matrix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matrix.o matrix.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

